export const getPokemonSpritePath = (id: number): string => {
  switch (id) {
    case 1:
      return require('../../src/assets/images/pokemon-sprites/1.png');
    case 2:
      return require('../../src/assets/images/pokemon-sprites/2.png');
    case 3:
      return require('../../src/assets/images/pokemon-sprites/3.png');
    case 4:
      return require('../../src/assets/images/pokemon-sprites/4.png');
    case 5:
      return require('../../src/assets/images/pokemon-sprites/5.png');
    case 6:
      return require('../../src/assets/images/pokemon-sprites/6.png');
    case 7:
      return require('../../src/assets/images/pokemon-sprites/7.png');
    case 8:
      return require('../../src/assets/images/pokemon-sprites/8.png');
    case 9:
      return require('../../src/assets/images/pokemon-sprites/9.png');
    case 10:
      return require('../../src/assets/images/pokemon-sprites/10.png');
    case 11:
      return require('../../src/assets/images/pokemon-sprites/11.png');
    case 12:
      return require('../../src/assets/images/pokemon-sprites/12.png');
    case 13:
      return require('../../src/assets/images/pokemon-sprites/13.png');
    case 14:
      return require('../../src/assets/images/pokemon-sprites/14.png');
    case 15:
      return require('../../src/assets/images/pokemon-sprites/15.png');
    case 16:
      return require('../../src/assets/images/pokemon-sprites/16.png');
    case 17:
      return require('../../src/assets/images/pokemon-sprites/17.png');
    case 18:
      return require('../../src/assets/images/pokemon-sprites/18.png');
    case 19:
      return require('../../src/assets/images/pokemon-sprites/19.png');
    case 20:
      return require('../../src/assets/images/pokemon-sprites/20.png');
    case 21:
      return require('../../src/assets/images/pokemon-sprites/21.png');
    case 22:
      return require('../../src/assets/images/pokemon-sprites/22.png');
    case 23:
      return require('../../src/assets/images/pokemon-sprites/23.png');
    case 24:
      return require('../../src/assets/images/pokemon-sprites/24.png');
    case 25:
      return require('../../src/assets/images/pokemon-sprites/25.png');
    case 26:
      return require('../../src/assets/images/pokemon-sprites/26.png');
    case 27:
      return require('../../src/assets/images/pokemon-sprites/27.png');
    case 28:
      return require('../../src/assets/images/pokemon-sprites/28.png');
    case 29:
      return require('../../src/assets/images/pokemon-sprites/29.png');
    case 30:
      return require('../../src/assets/images/pokemon-sprites/30.png');
    case 31:
      return require('../../src/assets/images/pokemon-sprites/31.png');
    case 32:
      return require('../../src/assets/images/pokemon-sprites/32.png');
    case 33:
      return require('../../src/assets/images/pokemon-sprites/33.png');
    case 34:
      return require('../../src/assets/images/pokemon-sprites/34.png');
    case 35:
      return require('../../src/assets/images/pokemon-sprites/35.png');
    case 36:
      return require('../../src/assets/images/pokemon-sprites/36.png');
    case 37:
      return require('../../src/assets/images/pokemon-sprites/37.png');
    case 38:
      return require('../../src/assets/images/pokemon-sprites/38.png');
    case 39:
      return require('../../src/assets/images/pokemon-sprites/39.png');
    case 40:
      return require('../../src/assets/images/pokemon-sprites/40.png');
    case 41:
      return require('../../src/assets/images/pokemon-sprites/41.png');
    case 42:
      return require('../../src/assets/images/pokemon-sprites/42.png');
    case 43:
      return require('../../src/assets/images/pokemon-sprites/43.png');
    case 44:
      return require('../../src/assets/images/pokemon-sprites/44.png');
    case 45:
      return require('../../src/assets/images/pokemon-sprites/45.png');
    case 46:
      return require('../../src/assets/images/pokemon-sprites/46.png');
    case 47:
      return require('../../src/assets/images/pokemon-sprites/47.png');
    case 48:
      return require('../../src/assets/images/pokemon-sprites/48.png');
    case 49:
      return require('../../src/assets/images/pokemon-sprites/49.png');
    case 50:
      return require('../../src/assets/images/pokemon-sprites/50.png');
    case 51:
      return require('../../src/assets/images/pokemon-sprites/51.png');
    case 52:
      return require('../../src/assets/images/pokemon-sprites/52.png');
    case 53:
      return require('../../src/assets/images/pokemon-sprites/53.png');
    case 54:
      return require('../../src/assets/images/pokemon-sprites/54.png');
    case 55:
      return require('../../src/assets/images/pokemon-sprites/55.png');
    case 56:
      return require('../../src/assets/images/pokemon-sprites/56.png');
    case 57:
      return require('../../src/assets/images/pokemon-sprites/57.png');
    case 58:
      return require('../../src/assets/images/pokemon-sprites/58.png');
    case 59:
      return require('../../src/assets/images/pokemon-sprites/59.png');
    case 60:
      return require('../../src/assets/images/pokemon-sprites/60.png');
    case 61:
      return require('../../src/assets/images/pokemon-sprites/61.png');
    case 62:
      return require('../../src/assets/images/pokemon-sprites/62.png');
    case 63:
      return require('../../src/assets/images/pokemon-sprites/63.png');
    case 64:
      return require('../../src/assets/images/pokemon-sprites/64.png');
    case 65:
      return require('../../src/assets/images/pokemon-sprites/65.png');
    case 66:
      return require('../../src/assets/images/pokemon-sprites/66.png');
    case 67:
      return require('../../src/assets/images/pokemon-sprites/67.png');
    case 68:
      return require('../../src/assets/images/pokemon-sprites/68.png');
    case 69:
      return require('../../src/assets/images/pokemon-sprites/69.png');
    case 70:
      return require('../../src/assets/images/pokemon-sprites/70.png');
    case 71:
      return require('../../src/assets/images/pokemon-sprites/71.png');
    case 72:
      return require('../../src/assets/images/pokemon-sprites/72.png');
    case 73:
      return require('../../src/assets/images/pokemon-sprites/73.png');
    case 74:
      return require('../../src/assets/images/pokemon-sprites/74.png');
    case 75:
      return require('../../src/assets/images/pokemon-sprites/75.png');
    case 76:
      return require('../../src/assets/images/pokemon-sprites/76.png');
    case 77:
      return require('../../src/assets/images/pokemon-sprites/77.png');
    case 78:
      return require('../../src/assets/images/pokemon-sprites/78.png');
    case 79:
      return require('../../src/assets/images/pokemon-sprites/79.png');
    case 80:
      return require('../../src/assets/images/pokemon-sprites/80.png');
    case 81:
      return require('../../src/assets/images/pokemon-sprites/81.png');
    case 82:
      return require('../../src/assets/images/pokemon-sprites/82.png');
    case 83:
      return require('../../src/assets/images/pokemon-sprites/83.png');
    case 84:
      return require('../../src/assets/images/pokemon-sprites/84.png');
    case 85:
      return require('../../src/assets/images/pokemon-sprites/85.png');
    case 86:
      return require('../../src/assets/images/pokemon-sprites/86.png');
    case 87:
      return require('../../src/assets/images/pokemon-sprites/87.png');
    case 88:
      return require('../../src/assets/images/pokemon-sprites/88.png');
    case 89:
      return require('../../src/assets/images/pokemon-sprites/89.png');
    case 90:
      return require('../../src/assets/images/pokemon-sprites/90.png');
    case 91:
      return require('../../src/assets/images/pokemon-sprites/91.png');
    case 92:
      return require('../../src/assets/images/pokemon-sprites/92.png');
    case 93:
      return require('../../src/assets/images/pokemon-sprites/93.png');
    case 94:
      return require('../../src/assets/images/pokemon-sprites/94.png');
    case 95:
      return require('../../src/assets/images/pokemon-sprites/95.png');
    case 96:
      return require('../../src/assets/images/pokemon-sprites/96.png');
    case 97:
      return require('../../src/assets/images/pokemon-sprites/97.png');
    case 98:
      return require('../../src/assets/images/pokemon-sprites/98.png');
    case 99:
      return require('../../src/assets/images/pokemon-sprites/99.png');
    case 100:
      return require('../../src/assets/images/pokemon-sprites/100.png');
    case 101:
      return require('../../src/assets/images/pokemon-sprites/101.png');
    case 102:
      return require('../../src/assets/images/pokemon-sprites/102.png');
    case 103:
      return require('../../src/assets/images/pokemon-sprites/103.png');
    case 104:
      return require('../../src/assets/images/pokemon-sprites/104.png');
    case 105:
      return require('../../src/assets/images/pokemon-sprites/105.png');
    case 106:
      return require('../../src/assets/images/pokemon-sprites/106.png');
    case 107:
      return require('../../src/assets/images/pokemon-sprites/107.png');
    case 108:
      return require('../../src/assets/images/pokemon-sprites/108.png');
    case 109:
      return require('../../src/assets/images/pokemon-sprites/109.png');
    case 110:
      return require('../../src/assets/images/pokemon-sprites/110.png');
    case 111:
      return require('../../src/assets/images/pokemon-sprites/111.png');
    case 112:
      return require('../../src/assets/images/pokemon-sprites/112.png');
    case 113:
      return require('../../src/assets/images/pokemon-sprites/113.png');
    case 114:
      return require('../../src/assets/images/pokemon-sprites/114.png');
    case 115:
      return require('../../src/assets/images/pokemon-sprites/115.png');
    case 116:
      return require('../../src/assets/images/pokemon-sprites/116.png');
    case 117:
      return require('../../src/assets/images/pokemon-sprites/117.png');
    case 118:
      return require('../../src/assets/images/pokemon-sprites/118.png');
    case 119:
      return require('../../src/assets/images/pokemon-sprites/119.png');
    case 120:
      return require('../../src/assets/images/pokemon-sprites/120.png');
    case 121:
      return require('../../src/assets/images/pokemon-sprites/121.png');
    case 122:
      return require('../../src/assets/images/pokemon-sprites/122.png');
    case 123:
      return require('../../src/assets/images/pokemon-sprites/123.png');
    case 124:
      return require('../../src/assets/images/pokemon-sprites/124.png');
    case 125:
      return require('../../src/assets/images/pokemon-sprites/125.png');
    case 126:
      return require('../../src/assets/images/pokemon-sprites/126.png');
    case 127:
      return require('../../src/assets/images/pokemon-sprites/127.png');
    case 128:
      return require('../../src/assets/images/pokemon-sprites/128.png');
    case 129:
      return require('../../src/assets/images/pokemon-sprites/129.png');
    case 130:
      return require('../../src/assets/images/pokemon-sprites/130.png');
    case 131:
      return require('../../src/assets/images/pokemon-sprites/131.png');
    case 132:
      return require('../../src/assets/images/pokemon-sprites/132.png');
    case 133:
      return require('../../src/assets/images/pokemon-sprites/133.png');
    case 134:
      return require('../../src/assets/images/pokemon-sprites/134.png');
    case 135:
      return require('../../src/assets/images/pokemon-sprites/135.png');
    case 136:
      return require('../../src/assets/images/pokemon-sprites/136.png');
    case 137:
      return require('../../src/assets/images/pokemon-sprites/137.png');
    case 138:
      return require('../../src/assets/images/pokemon-sprites/138.png');
    case 139:
      return require('../../src/assets/images/pokemon-sprites/139.png');
    case 140:
      return require('../../src/assets/images/pokemon-sprites/140.png');
    case 141:
      return require('../../src/assets/images/pokemon-sprites/141.png');
    case 142:
      return require('../../src/assets/images/pokemon-sprites/142.png');
    case 143:
      return require('../../src/assets/images/pokemon-sprites/143.png');
    case 144:
      return require('../../src/assets/images/pokemon-sprites/144.png');
    case 145:
      return require('../../src/assets/images/pokemon-sprites/145.png');
    case 146:
      return require('../../src/assets/images/pokemon-sprites/146.png');
    case 147:
      return require('../../src/assets/images/pokemon-sprites/147.png');
    case 148:
      return require('../../src/assets/images/pokemon-sprites/148.png');
    case 149:
      return require('../../src/assets/images/pokemon-sprites/149.png');
    case 150:
      return require('../../src/assets/images/pokemon-sprites/150.png');
    default:
      return require('../../src/assets/images/pokemon-sprites/0.png');
  }
};
