import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  baseContainer: {
    flex: 1,
    height: '100%',
  },
  container: {
    marginHorizontal: 40,
  },
  teamContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: '100%',
    paddingBottom: 15,
  },
  pastTeamsContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    right: 10,
    width: '105%',
    marginVertical: 10,
    alignItems: 'center',
  },
  header: {
    paddingTop: 25,
    fontSize: 19,
    color: 'rgba(41, 50, 60, 0.9)',
    fontWeight: '400',
    fontFamily: 'PressStart2P-Regular',
  },
  pastTeamTitles: {
    paddingTop: 25,
    fontSize: 14,
    color: 'rgba(41, 50, 60, 0.9)',
    fontWeight: '600',
    fontFamily: 'PressStart2P-Regular',
    paddingBottom: 10,
    marginLeft: 50,
  },
  previousTeamLoadBtn: {
    backgroundColor: 'cyan',
    paddingVertical: 4,
    marginTop: 2,
    paddingHorizontal: 16,
    borderRadius: 5,
    marginRight: 10,
  },
  previousTeamDeleteText: {
    color: 'white',
  },
  previousTeamDeleteBtn: {
    backgroundColor: 'maroon',
    paddingVertical: 4,
    marginTop: 2,
    paddingHorizontal: 16,
    borderRadius: 5,
  },
  subtitle: {
    fontSize: 15,
    color: 'rgba(41, 50, 60, 0.9)',
    fontWeight: '800',
  },
  teamName: {
    paddingLeft: 5,
    fontSize: 15,
    fontWeight: '500',
    color: 'black',
    placeholderTextColor: 'black',
    fontStyle: 'italic',
    maxWidth: 140,
    flexWrap: 'wrap',
    flexShrink: 1,
  },
  currentTeamContainer: {
    paddingTop: 15,
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    justifyContent: 'space-between',
  },
  teamNameInput: {
    fontSize: 18,
    fontWeight: '500',
    flex: 1,
    marginRight: 5,
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderWidth: 1,
    borderRadius: 5,
  },
  errorText: {
    paddingTop: 35,
    fontFamily: 'PressStart2P-Regular',
    fontSize: 32,
    textAlign: 'center',
  },
  previousTeamName: {
    fontSize: 15,
    color: 'rgba(41, 50, 60, 0.9)',
    fontWeight: '600',
    fontStyle: 'italic',
  },
  previousTeamContainer: {
    width: '100%',
    paddingLeft: 50,
    paddingRight: 40,
  },
  previousTeamBaseContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 10,
  },
  scrollViewContainer: {
    flex: 1,
    paddingTop: 10,
  },
});
